<?php

namespace App\FormationBundle\Repository;
use App\FormationBundle\Repository\Interfaces\VoteRepositoryInterface;

/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends AbstractGenericRepository implements VoteRepositoryInterface
{
}
