services:
    app_formation.media_repository:
        class: App\FormationBundle\Repository\MediaRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments: ['App\FormationBundle\Entity\Media']
        lazy: true

    app_formation.vote_repository:
        class: App\FormationBundle\Repository\VoteRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments: ['App\FormationBundle\Entity\Vote']
        lazy: true
