services:
    app_formation.media_manager:
        class: App\FormationBundle\Entity\Manager\MediaManager
        arguments: ["@app_formation.media_repository", "@security.token_storage"]

    app_formation.vote_manager:
        class: App\FormationBundle\Entity\Manager\VoteManager
        arguments: ["@app_formation.vote_repository", "@security.token_storage"]

    app_formation.mailer_service:
        class: App\FormationBundle\Service\MailerService
        arguments:
            - "@mailer"

    app_formation.contact.manager:
        class: App\FormationBundle\Entity\Manager\ContactManager
        arguments: ['@app_formation.mailer_service', '@twig', '@translator','AppFormationBundle:Mail:contact_mail.html.twig', '%email_from%', '%mailer_user%']